name: smooth_dropdown_example
description: A demo app for the smooth_dropdown package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_dropdown:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

flutter:
  uses-material-design: true
